/******************************************************************************
*  Generated by PSoC Designer 
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "Counter16.h"
#include "LCD.h"
#include "SCDAC.h"
#include "SCGain.h"

#endif
