;;*****************************************************************************
;;*****************************************************************************
;;  FILENAME: FanPWMINT.asm
;;   Version: 2.60, Updated on 2011/3/29 at 14:30:52
;;  Generated by PSoC Designer 5.1.2110.0
;;
;;  DESCRIPTION: PWM8 Interrupt Service Routine
;;-----------------------------------------------------------------------------
;;  Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
;;*****************************************************************************
;;*****************************************************************************

include "m8c.inc"
include "FanPWM.inc"
include "memory.inc"


;-----------------------------------------------
;  Global Symbols
;-----------------------------------------------
export  _FanPWM_ISR


AREA InterruptRAM (RAM,REL,CON)

;@PSoC_UserCode_INIT@ (Do not change this line.)
;---------------------------------------------------
; Insert your custom declarations below this banner
;---------------------------------------------------

;------------------------
; Includes
;------------------------

	
;------------------------
;  Constant Definitions
;------------------------


;------------------------
; Variable Allocation
;------------------------


;---------------------------------------------------
; Insert your custom declarations above this banner
;---------------------------------------------------
;@PSoC_UserCode_END@ (Do not change this line.)


AREA UserModules (ROM, REL)

;-----------------------------------------------------------------------------
;  FUNCTION NAME: _FanPWM_ISR
;
;  DESCRIPTION: Unless modified, this implements only a null handler stub.
;
;-----------------------------------------------------------------------------
;

_FanPWM_ISR:

   ;@PSoC_UserCode_BODY@ (Do not change this line.)
   ;---------------------------------------------------
   ; Insert your custom assembly code below this banner
   ;---------------------------------------------------
   ;   NOTE: interrupt service routines must preserve
   ;   the values of the A and X CPU registers.
   
   	RDIxLT0: equ 0xb3
   		dec [_wControlState + 1]
		sbb [_wControlState],0
		jnz MoreThan255
		cmp [_wControlState + 1], 20
		jnz Not20
		
	State20:
		mov reg[PRT1DR], 0x40
		or reg[RDIxLT0], 0x0f
		reti
		
	Not20:
		cmp[_wControlState+1],0
		jnz NotZero
	
	State0:
		mov reg[PRT1DR] , 0x00
		and reg[RDIxLT0] , 0xf3
		mov [_wControlState] , 3
		mov [_wControlState + 1] , 232
		reti
		
	NotZero:
	MoreThan255:
   ;---------------------------------------------------
   ; Insert your custom assembly code above this banner
   ;---------------------------------------------------
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function below this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   
   ;PRESERVE_CPU_CONTEXT
   ;lcall _My_C_Function
   ;RESTORE_CPU_CONTEXT
   
   ;---------------------------------------------------
   ; Insert a lcall to a C function above this banner
   ; and un-comment the lines between these banners
   ;---------------------------------------------------
   ;@PSoC_UserCode_END@ (Do not change this line.)

   reti


; end of file FanPWMINT.asm
