/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#include <m8c.h>
// RefHiOut address and mask defines
#pragma	ioport	RefHiOut_Data_ADDR:	0x0
BYTE			RefHiOut_Data_ADDR;
#pragma	ioport	RefHiOut_DriveMode_0_ADDR:	0x100
BYTE			RefHiOut_DriveMode_0_ADDR;
#pragma	ioport	RefHiOut_DriveMode_1_ADDR:	0x101
BYTE			RefHiOut_DriveMode_1_ADDR;
#pragma	ioport	RefHiOut_DriveMode_2_ADDR:	0x3
BYTE			RefHiOut_DriveMode_2_ADDR;
#pragma	ioport	RefHiOut_GlobalSelect_ADDR:	0x2
BYTE			RefHiOut_GlobalSelect_ADDR;
#pragma	ioport	RefHiOut_IntCtrl_0_ADDR:	0x102
BYTE			RefHiOut_IntCtrl_0_ADDR;
#pragma	ioport	RefHiOut_IntCtrl_1_ADDR:	0x103
BYTE			RefHiOut_IntCtrl_1_ADDR;
#pragma	ioport	RefHiOut_IntEn_ADDR:	0x1
BYTE			RefHiOut_IntEn_ADDR;
#define RefHiOut_MASK 0x8
// AGndOut address and mask defines
#pragma	ioport	AGndOut_Data_ADDR:	0x0
BYTE			AGndOut_Data_ADDR;
#pragma	ioport	AGndOut_DriveMode_0_ADDR:	0x100
BYTE			AGndOut_DriveMode_0_ADDR;
#pragma	ioport	AGndOut_DriveMode_1_ADDR:	0x101
BYTE			AGndOut_DriveMode_1_ADDR;
#pragma	ioport	AGndOut_DriveMode_2_ADDR:	0x3
BYTE			AGndOut_DriveMode_2_ADDR;
#pragma	ioport	AGndOut_GlobalSelect_ADDR:	0x2
BYTE			AGndOut_GlobalSelect_ADDR;
#pragma	ioport	AGndOut_IntCtrl_0_ADDR:	0x102
BYTE			AGndOut_IntCtrl_0_ADDR;
#pragma	ioport	AGndOut_IntCtrl_1_ADDR:	0x103
BYTE			AGndOut_IntCtrl_1_ADDR;
#pragma	ioport	AGndOut_IntEn_ADDR:	0x1
BYTE			AGndOut_IntEn_ADDR;
#define AGndOut_MASK 0x10
// RefLoOut address and mask defines
#pragma	ioport	RefLoOut_Data_ADDR:	0x0
BYTE			RefLoOut_Data_ADDR;
#pragma	ioport	RefLoOut_DriveMode_0_ADDR:	0x100
BYTE			RefLoOut_DriveMode_0_ADDR;
#pragma	ioport	RefLoOut_DriveMode_1_ADDR:	0x101
BYTE			RefLoOut_DriveMode_1_ADDR;
#pragma	ioport	RefLoOut_DriveMode_2_ADDR:	0x3
BYTE			RefLoOut_DriveMode_2_ADDR;
#pragma	ioport	RefLoOut_GlobalSelect_ADDR:	0x2
BYTE			RefLoOut_GlobalSelect_ADDR;
#pragma	ioport	RefLoOut_IntCtrl_0_ADDR:	0x102
BYTE			RefLoOut_IntCtrl_0_ADDR;
#pragma	ioport	RefLoOut_IntCtrl_1_ADDR:	0x103
BYTE			RefLoOut_IntCtrl_1_ADDR;
#pragma	ioport	RefLoOut_IntEn_ADDR:	0x1
BYTE			RefLoOut_IntEn_ADDR;
#define RefLoOut_MASK 0x20
