/******************************************************************************
*  Generated by PSoC Designer 5.1.2306
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "RefAgndMux.h"
#include "RefHiMux.h"
#include "RefLoMux.h"

#endif
