//*****************************************************************************
//*****************************************************************************
//  FILENAME:  RefHiMux.h
//  Version: 1.3, Updated on 2011/6/28 at 6:9:55
//  Generated by PSoC Designer 5.1.2306
//
//  DESCRIPTION:
//  DESCRIPTION: RefMux User Module C Language interface file.
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2011. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef RefHiMux_INCLUDE
#define RefHiMux_INCLUDE

#include <m8c.h>

//-------------------------------------------------
// Constants for RefHiMux API's.
//-------------------------------------------------
#define RefHiMux_MUXOFF                0x00
#define RefHiMux_PMUXOUT               0x10
#define RefHiMux_AGND                  0x14
#define RefHiMux_REFLO                 0x18
#define RefHiMux_REFHI                 0x1C

#define RefHiMux_OFF                   0
#define RefHiMux_LOWPOWER              1
#define RefHiMux_MEDPOWER              2
#define RefHiMux_HIGHPOWER             3


#pragma fastcall16 RefHiMux_Start
#pragma fastcall16 RefHiMux_SetPower
#pragma fastcall16 RefHiMux_Stop
#pragma fastcall16 RefHiMux_RefSelect

//-------------------------------------------------
// Prototypes of the RefHiMux API.
//-------------------------------------------------
extern void RefHiMux_Start(BYTE bPower);
extern void RefHiMux_SetPower(BYTE bPower);
extern void RefHiMux_Stop( void );
extern void RefHiMux_RefSelect(BYTE bRef);


//-------------------------------------------------
// Register Addresses for RefHiMux
//-------------------------------------------------

#pragma ioport  RefHiMux_REFMUX_CR0:    0x071
BYTE            RefHiMux_REFMUX_CR0;
#pragma ioport  RefHiMux_REFMUX_CR1:    0x072
BYTE            RefHiMux_REFMUX_CR1;
#pragma ioport  RefHiMux_REFMUX_CR2:    0x073
BYTE            RefHiMux_REFMUX_CR2;
#pragma ioport  RefHiMux_REFMUX_CR3:    0x070
BYTE            RefHiMux_REFMUX_CR3;

#endif
// end of file RefHiMux.
