/******************************************************************************
*  Generated by PSoC Designer 
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "LCD.h"
#include "Timer.h"

#endif
